print("Hello you")
print("mijn naam is abdulrahman")
naam = input("Wat is jou naam?")
print("Hello" + naam)
age =2022 - int(input("in welke jaar ben je geboren?"))
print (age)
print(" welkom " + naam +"over 5 jaar wordt je" + str(age+5)+"jaar oud" )
